### ISSUE TITLE
Improve the experience of someone who's looking to understand recipients

### ISSUE THREAD

**Issue by robredpath** [ThreeSixtyGiving/grantnav#688] opened 2021-05-18 14:46 UTC
**Is your feature request related to a problem? Please describe.**

There are two ways that we think people use GN in relation to recipient info - looking for grants to a particular org, and understanding the recipients for a set of grants. 

**Describe the solution you'd like**

A more usable recipient filter (eg search)
Better docs around understanding recipients 
A way of understanding the recipients of a set of grants
The recipients page being more informative

**Describe alternatives you've considered**

Possibilities include:
* The code we've already written for search within recipient facet
* A new index in elastic for the recipients to power some autocomplete functionality for that search box
* Displaying an alternative control where the recipient org facet is for larger results set

**Additional context**

**Comment by robredpath** [comment] 2021-05-18 14:57
![](https://github.trello.services/images/mini-trello-icon.png) [GrantNav filters](https://trello.com/c/Ax9J23gJ/153-grantnav-filters)

**Comment by robredpath** [comment] 2021-06-02 13:39
Discussed   with @mariongalley today. 

@kindly - let's work out in some more detail what the new recipients index work would look like - we've got a tentative green light for that, but it'd be good to properly understand it before we fully commit. 

Then, we'll also need some copy for the recipient and recipients pages - I'll talk to the ODSC team and work out where we could add some copy as an interim measure ahead of getting more design done. This could just be a little (i) info box to link to the help site.

**Comment by mariongalley** [comment] 2021-06-22 13:44
# David & Marion comments on recipient filter
Search no longer works when you have a recipient already selected. If this is multiselect it needs to behave the same way after you've selected one or more recipients as when none are selected yet.

**Comment by mariongalley** [comment] 2021-06-23 11:09
@michaelwood @kindly happy for this issue to be closed but per my last comment, will it be possible to ensure the search continues to work after a recipient has already been selected? Should that be raised as a separate issue/bug?

**Comment by mariongalley** [comment] 2021-06-23 11:13
Repro steps:
First recipient search: behaves as expected, shows relevant results.
![image](https://user-images.githubusercontent.com/82958988/123087082-0e5bc480-d41c-11eb-9e0b-3d44b120462a.png)
Select a recipient and start a second search: list of recipients is in the default order, not showing relevant results and preventing me from selecting another recipient that doesn't appear in the default list.
![image](https://user-images.githubusercontent.com/82958988/123087355-5a0e6e00-d41c-11eb-8cc0-a6fb1dc717d7.png)

**Comment by mariongalley** [comment] 2021-06-23 11:15
Ah my mistake, looks like this was fixed in #756 - still getting my head around Github, ignore me!

**Comment by kindly** [comment] 2021-06-23 12:02
@mariongalley this is now deployed.  Would be great if you could check this is as you expect.

**Comment by mariongalley** [comment] 2021-06-23 17:07
Hmmm, I tried testing it earlier and was struggling a lot with slowness, but it looked as though it was letting me search for a second recipient after I'd selected one (but not a 3rd after I'd selected 2).

Just tried again and now it doesn't seem to be searching for a second recipient when I have one selected. This seems like user error on my part, unless a subsequent push has broken something @kindly

**Comment by kindly** [comment] 2021-06-23 17:57
I can not reproduce this sadly, tried 5 recipients and still the search seems to be working.  It is slighly slow for me when the main serach is looking at all the data.  Also there is a 0.1 delay after typing is finished so as not to do too many requests to the server. This could be potentially reduced.
  
The only things I can think of is the server being slow or the internet connection is slow for some reason or there is a javascript error caused by putting in a particular input (that I am not doing).

So if the search is still not working for you then the exact steps you are doing would be great.

**Comment by mariongalley** [comment] 2021-06-24 11:00
@kindly Retested this morning and it seems to work as designed. I think the issue is due to a combination of slowness and it reloading the results every time it appeared to be intermittently working/not working. I'm not sure if there's all that much we can do about that. We could add some kind of "buffering" that stops you trying to add another until the results have reloaded, or we could add an "Apply" button so it doesn't reload until you've finished your selection. I'm not sure either is better than the current behaviour though. Thoughts @drkane?

**Comment by mariongalley** [comment] 2021-06-24 13:08
Call with Jared, David R, Michael and David K: The filter does work as designed, but we need to account for people having slow connections and find some way of making it clearer that the results are refreshing and/or prevent them from applying another filter while that happens.

**Comment by robredpath** [comment] 2021-07-08 10:20
@mariongalley I've added https://trello.com/c/NzU9pyTl/181-improve-the-experience-of-using-grantnav-on-slower-connections-or-devices to address the wider question of slow facets - that's been an issue since the start, and these new facets have made it more obvious. 

Given that, can we close this and look for a more general solution?

**Comment by mariongalley** [comment] 2021-07-08 10:57
@robredpath Hi, yes that's fine by me, we can close this

**Closed by mariongalley** 2021-07-08 10:57 UTC
Labels: filters, issue needs clarification
