### ISSUE TITLE
How can we link Funders to Publishers

### ISSUE THREAD

**Issue by mariongalley** [ThreeSixtyGiving/grantnav#832] opened 2022-02-17 11:04 UTC
We've talked about this already, but it sounds like we would need to look at Salesforce to match up Funders' Org IDs to their Publisher prefixes in order to display the As Publisher section. It would be good to explore what our options are.

What this will look like in future: publishing Funders' Org Pages that don't have an As Publisher section e.g. [Greater London Authority](http://insightsng.vs.mythic-beasts.com:8888/org/GB-LAE-GLA) would have an As Publisher section e.g. [Arcadia](http://insightsng.vs.mythic-beasts.com:8888/org/360G-ArcadiaFund).

**Comment by robredpath** [comment] 2022-02-17 17:44
There are a handful of funders who use their 360 publisher prefix as their funder ID - so this doesn't affect every publisher/funder. 

Ideally, this would be something that we resolve in the data rather than in Salesforce - with Salesforce being the backup option. 

The metadata might be the place to do it - some way to declare a publisher-funder ID relationship?

**Comment by mariongalley** [comment] 2022-02-18 09:15
> Ideally, this would be something that we resolve in the data rather than in Salesforce [...]
> The metadata might be the place to do it - some way to declare a publisher-funder ID relationship?

Does that require an update to the standard itself? Or merely guidance explaining how to include both publisher prefix and org ID in the data?

> with Salesforce being the backup option

I agree we should use Salesforce as a backup - if we've never told publishers we expect them to do this before, we can't justify using it as a 'teachable moment' to only link up their GrantNav page if they've done it.

**Comment by robredpath** [comment] 2022-02-28 13:37
>  some way to declare a publisher-funder ID relationship?
> Does that require an update to the standard itself?

For the straightforward case of a single organisation that has a single identifier, then they can just put the org ID that they use for funding into the `Publisher:Identifier` field: I know some publishers already do this. 

For the more complex case, then yes, we would need to look at a change to the standard. It needn't be a complex change, but would need thinking through: my initial thought would be to add a `Funding Identifiers` array to the `Publisher` object.

**Comment by mariongalley** [comment] 2022-03-03 15:59
> Current GrantNav already has a link between publishers and funders on the current publisher pages, in the tables - '[Funders Covered](https://grantnav.threesixtygiving.org/publisher/360G-NLHF)' Can't this data be used - I'm assuming this is derived from the data itself?

And new GrantNav has this too! How come we can know that grants funded by GLA are also published by GLA and link to the [GLA's publisher page](http://insightsng.vs.mythic-beasts.com:8888/org/360G-GLA) from the [GLA's funder page](http://insightsng.vs.mythic-beasts.com:8888/org/GB-LAE-GLA) but not display the publisher card at the bottom of the page?

**Comment by robredpath** [comment] 2022-03-08 14:25
The link that currently exists between publishers and funders is "which organisation publishes grants made by this other organisation?": sometimes they're the same organisation, but sometimes they're not! 

If the organisation uses the same org ID for publication and funding, then we've already got all the info that we need: take, for example Arcadia, who use their 360G prefix for their funding (such as on https://grantnav.threesixtygiving.org/grant/360G-ArcadiaFund-4498 ), or Friends Provident Foundation, whose publication uses their GB-CHC org ID (see https://grantnav.threesixtygiving.org/publisher/GB-CHC-1087053 ). 

Where an organisation uses a different org ID for publication and funding, then we don't have all the information that we need. In the case of the GLA, we know that `360G-GLA` publish data about grants given by `GB-LAE-GLA` but we have no way of determining that `360G-GLA` and `GB-LAE-GLA` are the same organisation. From the perspective of the data, it's the same as `360G-cabinetoffice` publishing data about grants given by `GB-GOR-D4` (MHCLG) - and in that case, they're not the same organisation. 

When I say "organisation uses" I'm conscious that in practice that's our Salesforce field: I assume that's at least notionally controlled by the publisher, but I'm not sure of the practical processes. 

The "funders covered" information comes from the data - but it starts with the publisher, not the funder. So, for each publisher, we can tell from the data which funders they publish information for. But, because we do support cases like the Cabinet Office publishing data about other departments, we can't use that information to infer the link in the other direction - that the organisation whose grants are being published is the same organisation as the one that did the publishing. 

By far the simplest way to fix this (technically speaking) would be for us to update our data in Salesforce - either by setting their publishing prefix to an org ID that we know that they use for funding (so that the situation with Friends Provident is the norm) or by adding a new field to Salesforce to contain a known funder ID for publishers. We could then publish that data in the registry JSON feed: it's an important piece of the data puzzle for anyone trying to work from source. 

The underlying principle of the data services work (which gave rise to the datastore, metadata, etc) was to ensure that publishers had control of information about themselves via their data: as far as possible, 360 should be collecting and publishing information about organisations via non-public / non-machine-readable means only when publishers aren't providing that for themselves. That reduces reliance on 360Giving (the organisation) for the data ecosystem, and means that the data is more useful when used outside of 360Giving data products. Pragmatically speaking, I know we're not very far along that journey, and it's not a particular priority, but I think it's an important principle to work to.

**Comment by michaelwood** [comment] 2022-03-21 18:22
David R and I talked about this and yes exactly as Rob said above ^ this is a source data issue rather than something we should fix at an application level.

We don't have a very viable workaround as essentially this is about two organisation identifiers not matching so we can't tell that they're the same organisation. Those identifiers aren't in our control so we could only guess at matching them which wouldn't be great.  

@mariongalley  can this be dropped from `pre-requisite for live`?

**Comment by mariongalley** [comment] 2022-03-22 09:19
> We don't have a very viable workaround as essentially this is about two organisation identifiers not matching so we can't tell that they're the same organisation.

What about Katherine's suggestion to get the mapping from Salesforce?

> this is a source data issue rather than something we should fix at an application level.

Is this a matter of principle rather than a technical objection? @michaelwood

**Comment by michaelwood** [comment] 2022-03-22 10:22
Doing a work-around with salesforce when there is a `Publisher:Identifier` field in the standard seems like setting down a path of having to manually maintain a copy of that data and then also having to have a mechanism for choosing the canonical version.

**Comment by mariongalley** [comment] 2022-04-13 12:06
So I think we have 3 options:

1. Never merge the Publisher and Funder sections onto the same page. Keep the Publisher page entirely separate as it is on the current Funder pages.
2. Use Salesforce field to determine when the Publisher and Funder are one and the same
    - If so, display "As Publisher" section on the funder page.
    - In the edge case where a Publisher is not also a funder, they need to keep their separate publisher page 
3. Always display the Publisher section on all Funder pages regardless of if they are the same organisation, just don't imply that they are the same org.
    - I don't think this would work as we link to the Publisher page from the Data Quality Dashboard, and so for Publishers that publish grants on behalf of several funders, how would we decide which Org page to link to? E.g. from the Cabinet Office publisher page of the Quality Dashboard

At the moment I'm leaning towards option 1 as it's probably not worth the investment required (I'm not sure if the 1 day estimate in the planio was to do 2 or 3 though). However, we'll have to revisit the Publisher page at some point as currently it doesn't add much value.

**Comment by kindly** [comment] 2022-04-13 13:08
> So I think we have 3 options:
> 
>     1. Never merge the Publisher and Funder sections onto the same page. Keep the Publisher page entirely separate as it is on the current Funder pages.

Seems like a fair option.

>     2. Use Salesforce field to determine when the Publisher and Funder are one and the same
>        
>        * If so, display "As Publisher" section on the funder page.
>        * In the edge case where a Publisher is not also a funder, they need to keep their separate publisher page

If the publisher is also a funder, I am not sure why we can not use the funder Org-ID as the id we have in Salesforce (not the 360G) one.  If we did that then the current approach already works and would be no additional work at least from the grantnav side.

>     3. Always display the Publisher section on all Funder pages regardless of if they are the same organisation, just don't imply that they are the same org.
>        
>        * I don't think this would work as we link to the Publisher page from the Data Quality Dashboard, and so for Publishers that publish grants on behalf of several funders, how would we decide which Org page to link to? E.g. from the Cabinet Office publisher page of the Quality Dashboard

I would say we could display this information on the Funders page but still have a seperate Publisher page, as that page would exist for the Org-Ids assigned to the publisher.

**Comment by robredpath** [comment] 2022-04-13 16:42
@KDuerden how would you feel about updating the data that we hold in Salesforce such that any organisation that publishes data and uses a non-360G prefix has their "360Giving prefix" field set to their external org ID. 

For example, for Somerset Community Foundation: setting their prefix to GB-COH-04530979 (the ID that they use in their data - https://grantnav.threesixtygiving.org/funder/GB-COH-04530979 ) instead of 360G-SomersetCF (which is how we currently identify them as a publisher - https://grantnav.threesixtygiving.org/publisher/360G-SomersetCF )

If there's a reason to not do that, then we can absolutely look for other options. But, I think that for the vast majority of cases, that would fix this issue without any changes to software.

**Comment by KDuerden** [comment] 2022-04-25 15:05
@robredpath I don't understand what you're asking. There are currently two funders who use a non-360G prefix as their prefix - using org ID instead. This is not recommended by the Standard (https://standard.threesixtygiving.org/en/latest/technical/identifiers/#get-your-prefix) 

These prefixes are in use in 360Giving data, so are you suggesting we change them in our systems or get them to change them?

**Comment by mariongalley** [comment] 2022-10-21 09:41
@michaelwood Is there an action still with us on this? For some reason I seem to remember the new field already existing and even you starting to use it, which would imply [1-3 above](https://github.com/ThreeSixtyGiving/grantnav/issues/832#issuecomment-1109906919) all being done. But the issue of not all Funder/Publisher orgs having their As Publisher section on their Org page persists.

**Comment by mariongalley** [comment] 2022-10-27 09:50
> Call with @robredpath, @KDuerden and myself:
> 
> * Katherine to let @michaelwood know to expose the Organisation Identifier field in SalesForce ( API name: Org_Identifier__c )

This is done.

> * Katherine to check exceptions & update the values if needed

This is still to do.

> * ODSC team to start using this new field to identify publishers and display as their Org ID (will also continue to display publisher prefix alongside this)

This is done.

**Comment by KDuerden** [comment] 2022-10-27 10:02
> Katherine to check exceptions & update the values if needed

Is there any data output that could be shared to help with the checking for exceptions? Those changes may prompt need for redirects (as previously raised in the context of the DQDashboard).

**Comment by mariongalley** [comment] 2022-10-27 10:16
@michaelwood Is there any way of identifying which Publishers have successfully been matched to Funders and which haven't, short of manually going through each Funder page?

**Comment by michaelwood** [comment] 2022-10-27 16:58
My querying of the datastore shows that all funder org ids are in the 'set' of publisher org ids, apart from MercersCompany. I can do various queries on the backend but need to know a bit more of what I'm looking for.

In #887 I've added the ability to supply a publisher prefix to the org page so there is now http://grantnav-org-pages.360dev1.vs.mythic-beasts.com/org/360G-MercersCompany which may be helpful to avoid needing to special case the links to organisations in various parts of grantnav.

Some of the stuff relating to publisher information and queries hasn't been changed since the beginning of grantnav 6 years ago so we're in slightly creaking parts of the codebase.

**Comment by mariongalley** [comment] 2022-11-07 16:36
@michaelwood http://grantnav-org-pages.360dev1.vs.mythic-beasts.com/org/GB-CHC-700510 Tyne & Wear CF seems to be missing an As Publisher section, so I think there may still be issues with the mapping in SF.

**Comment by KDuerden** [comment] 2022-11-10 12:38
Very helpful, I'm working through these at the moment to work out which can be resolved through updates to Salesforce.

**Comment by KDuerden** [comment] 2022-11-10 13:06
For 5 of these, Tyne & Wear CF, Somerset CF, Trafford Housing Trust, One Manchester and Joseph Rowntree Housing Trust the issue is that the funder identifies itself in its data with an org ID, but FTC prioritises a different type.

I believe Salesforce should store the org ID of the funder as the one they use to identify themselves. As their org IDs are all correct, we can't justify asking them to make a change.

It doesn't need to be part of MVP but is there potential for Datastore linking of publishers to funders to make use of the linked orgs/org IDs data when working out when to link?

**Comment by mariongalley** [comment] 2022-11-16 13:41
Suggest we close this and raise a new issue @michaelwood , as I think we can say we've successfully linked Funders to Publishers, but we now have an issue with the prioritisation of identifiers for the edge cases above. Not sure how to define the new issue so suggest either you or @KDuerden writes the issue before we close this.

**Comment by KDuerden** [comment] 2022-11-16 14:59
Attempted to set it out here: https://github.com/ThreeSixtyGiving/grantnav/issues/917

**Closed** 2022-11-16 15:00 UTC
Labels: enhancement / new feature, Org pages, Pre-requisite for live
